[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/static/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
